
#define module_name GenomeTools
#undef  module_name

#define module_onload DaoGenomeTools_Setup
#undef  module_onload


#define CLANGDAO_NULLABLE_POINTERS


#define x_dao_hint_unsupported(eb) gt_encseq_builder_create_esq_tab(GtEncseqBuilder*)
#undef x_dao_hint_unsupported

#define x_dao_hint_unsupported(eb) gt_encseq_builder_do_not_create_esq_tab(GtEncseqBuilder*)
#undef x_dao_hint_unsupported




#define dao__gt_diagram_new_from_array_dao_hint_userwrapper( features_dao_hint_daotype_GtArray_OR_list_LT_GtFeatureNode_GT, range_dao_hint_daotype_GtRange_OR_tuple_LT_int_COMMA_int_GT, style ) gt_diagram_new_from_array(GtArray*,const GtRange*,GtStyle*)


#define GtCDSStream_dao_hint() GtCDSStream
#define GtMD5ToIDStream_dao_hint() GtMD5ToIDStream
#define GtIDToMD5Stream_dao_hint() GtIDToMD5Stream
#define GtInterFeatureStream_dao_hint() GtInterFeatureStream
#define GtMergeFeatureStream_dao_hint() GtMergeFeatureStream
#define GtExtractFeatureStream_dao_hint() GtExtractFeatureStream


#define GtCanvasCairoContext_dao_hint_base_GtCanvas() GtCanvasCairoContext
#define GtCanvasCairoFile_dao_hint_base_GtCanvas() GtCanvasCairoFile
#define GtCustomTrackExample_dao_hint_base_GtCustomTrack() GtCustomTrackExample
#define GtCustomTrackGcContent_dao_hint_base_GtCustomTrack() GtCustomTrackGcContent
#define GtCustomTrackScriptWrapper_dao_hint_base_GtCustomTrack() GtCustomTrackScriptWrapper
#define GtFeatureIndexMemory_dao_hint_base_GtFeatureIndex() GtFeatureIndexMemory
#define GtFeatureVisitor_dao_hint_base_GtNodeVisitor() GtFeatureVisitor
#define GtGraphicsCairo_dao_hint_base_GtGraphics() GtGraphicsCairo
#define GtLineBreakerBases_dao_hint_base_GtLineBreaker() GtLineBreakerBases
#define GtLineBreakerCaptions_dao_hint_base_GtLineBreaker() GtLineBreakerCaptions
#define GtTextWidthCalculatorCairo_dao_hint_base_GtTextWidthCalculator() GtTextWidthCalculatorCairo
#define GtCodonIteratorEncseq_dao_hint_base_GtCodonIterator() GtCodonIteratorEncseq
#define GtCodonIteratorSimple_dao_hint_base_GtCodonIterator() GtCodonIteratorSimple
#define GtExampleA_dao_hint_base_GtExample() GtExampleA
#define GtExampleB_dao_hint_base_GtExample() GtExampleB
#define GtFastaReaderFSM_dao_hint_base_GtFastaReader() GtFastaReaderFSM
#define GtFastaReaderRec_dao_hint_base_GtFastaReader() GtFastaReaderRec
#define GtFastaReaderSeqIt_dao_hint_base_GtFastaReader() GtFastaReaderSeqIt
#define GtSeqIteratorFastQ_dao_hint_base_GtSeqIterator() GtSeqIteratorFastQ
#define GtSeqIteratorSequenceBuffer_dao_hint_base_GtSeqIterator() GtSeqIteratorSequenceBuffer
#define GtSequenceBufferEMBL_dao_hint_base_GtSequenceBuffer() GtSequenceBufferEMBL
#define GtSequenceBufferFasta_dao_hint_base_GtSequenceBuffer() GtSequenceBufferFasta
#define GtSequenceBufferFastQ_dao_hint_base_GtSequenceBuffer() GtSequenceBufferFastQ
#define GtSequenceBufferGB_dao_hint_base_GtSequenceBuffer() GtSequenceBufferGB
#define GtSequenceBufferPlain_dao_hint_base_GtSequenceBuffer() GtSequenceBufferPlain
#define CustomStream_dao_hint_base_GtNodeStream() CustomStream
#define GtAddIDsStream_dao_hint_base_GtNodeStream() GtAddIDsStream
#define GtAddIDsVisitor_dao_hint_base_GtNodeVisitor() GtAddIDsVisitor
#define GtBEDInStream_dao_hint_base_GtNodeStream() GtBEDInStream
#define GtBufferStream_dao_hint_base_GtNodeStream() GtBufferStream
#define GtCDSCheckStream_dao_hint_base_GtNodeStream() GtCDSCheckStream
#define GtCDSCheckVisitor_dao_hint_base_GtNodeVisitor() GtCDSCheckVisitor
#define GtCDSVisitor_dao_hint_base_GtNodeVisitor() GtCDSVisitor
#define GtChseqidsStream_dao_hint_base_GtNodeStream() GtChseqidsStream
#define GtCommentNode_dao_hint_base_GtGenomeNode() GtCommentNode
#define GtCSAStream_dao_hint_base_GtNodeStream() GtCSAStream
#define CSAVisitor_dao_hint_base_GtNodeVisitor() CSAVisitor
#define GtDupFeatureVisitor_dao_hint_base_GtNodeVisitor() GtDupFeatureVisitor
#define GtEOFNode_dao_hint_base_GtGenomeNode() GtEOFNode
#define GtExtractFeatureVisitor_dao_hint_base_GtNodeVisitor() GtExtractFeatureVisitor
#define GtGFF3InStream_dao_hint_base_GtNodeStream() GtGFF3InStream
#define GtGFF3InStreamPlain_dao_hint_base_GtNodeStream() GtGFF3InStreamPlain
#define GtGFF3OutStream_dao_hint_base_GtNodeStream() GtGFF3OutStream
#define GtGFF3Visitor_dao_hint_base_GtNodeVisitor() GtGFF3Visitor
#define GtGTFInStream_dao_hint_base_GtNodeStream() GtGTFInStream
#define GtGTFVisitor_dao_hint_base_GtNodeVisitor() GtGTFVisitor
#define GtSeqidsToMD5Visitor_dao_hint_base_GtNodeVisitor() GtSeqidsToMD5Visitor
#define GtInterFeatureVisitor_dao_hint_base_GtNodeVisitor() GtInterFeatureVisitor
#define GtMD5ToSeqidsVisitor_dao_hint_base_GtNodeVisitor() GtMD5ToSeqidsVisitor
#define GtMergeFeatureVisitor_dao_hint_base_GtNodeVisitor() GtMergeFeatureVisitor
#define GtMergeStream_dao_hint_base_GtNodeStream() GtMergeStream
#define GtRegionNode_dao_hint_base_GtGenomeNode() GtRegionNode
#define GtRegionCovVisitor_dao_hint_base_GtNodeVisitor() GtRegionCovVisitor
#define GtScriptWrapperStream_dao_hint_base_GtNodeStream() GtScriptWrapperStream
#define GtScriptWrapperVisitor_dao_hint_base_GtNodeVisitor() GtScriptWrapperVisitor
#define GtSelectStream_dao_hint_base_GtNodeStream() GtSelectStream
#define GtSelectVisitor_dao_hint_base_GtNodeVisitor() GtSelectVisitor
#define GtSequenceNode_dao_hint_base_GtGenomeNode() GtSequenceNode
#define GtSortStream_dao_hint_base_GtNodeStream() GtSortStream
#define GtSpliceSiteInfoStream_dao_hint_base_GtNodeStream() GtSpliceSiteInfoStream
#define GtSpliceSiteInfoVisitor_dao_hint_base_GtNodeVisitor() GtSpliceSiteInfoVisitor
#define GtStatStream_dao_hint_base_GtNodeStream() GtStatStream
#define GtStatVisitor_dao_hint_base_GtNodeVisitor() GtStatVisitor
#define GtTargetbestSelectStream_dao_hint_base_GtNodeStream() GtTargetbestSelectStream
#define GtTidyRegionNodeStream_dao_hint_base_GtNodeStream() GtTidyRegionNodeStream
#define GtTidyRegionNodeVisitor_dao_hint_base_GtNodeVisitor() GtTidyRegionNodeVisitor
#define GtTypeCheckerBuiltin_dao_hint_base_GtTypeChecker() GtTypeCheckerBuiltin
#define GtTypeCheckerOBO_dao_hint_base_GtTypeChecker() GtTypeCheckerOBO
#define GtUniqStream_dao_hint_base_GtNodeStream() GtUniqStream
#define GtVisitorStream_dao_hint_base_GtNodeStream() GtVisitorStream
#define GthGFF3PGLVisitor_dao_hint_base_GthPGLVisitor() GthGFF3PGLVisitor
#define GthGFF3SAVisitor_dao_hint_base_GthSAVisitor() GthGFF3SAVisitor
#define GthTxtPGLVisitor_dao_hint_base_GthPGLVisitor() GthTxtPGLVisitor
#define GthTxtSAVisitor_dao_hint_base_GthSAVisitor() GthTxtSAVisitor
#define GthXMLFinalSAVisitor_dao_hint_base_GthSAVisitor() GthXMLFinalSAVisitor
#define GthXMLInterSAVisitor_dao_hint_base_GthSAVisitor() GthXMLInterSAVisitor
#define GthXMLPGLVisitor_dao_hint_base_GthPGLVisitor() GthXMLPGLVisitor
#define GtLTRVisitor_dao_hint_base_GtNodeVisitor() GtLTRVisitor
#define GtLTRdigestStream_dao_hint_base_GtNodeStream() GtLTRdigestStream
#define GtLTRFileOutStream_dao_hint_base_GtNodeStream() GtLTRFileOutStream
#define GtLTRharvestFastaOutVisitor_dao_hint_base_GtNodeVisitor() GtLTRharvestFastaOutVisitor
#define GtLTRharvestStream_dao_hint_base_GtNodeStream() GtLTRharvestStream
#define GtLTRharvestTaboutVisitor_dao_hint_base_GtNodeVisitor() GtLTRharvestTaboutVisitor




#if 1

#define dao_gt_block_new_dao_hint_new_GtBlock() gt_block_new
#define dao_gt_block_new_from_node_dao_hint_new_GtBlock() gt_block_new_from_node
#define dao_gt_canvas_cairo_context_new_dao_hint_new_GtCanvasCairoContext() gt_canvas_cairo_context_new
#define dao_gt_canvas_cairo_file_new_dao_hint_new_GtCanvasCairoFile() gt_canvas_cairo_file_new
#define dao_gt_canvas_class_new_dao_hint_new_GtCanvasClass() gt_canvas_class_new
#define dao_gt_color_new_dao_hint_new_GtColor() gt_color_new
#define dao_gt_custom_track_example_new_dao_hint_new_GtCustomTrackExample() gt_custom_track_example_new
#define dao_gt_custom_track_gc_content_new_dao_hint_new_GtCustomTrackGcContent() gt_custom_track_gc_content_new
#define dao_gt_custom_track_class_new_dao_hint_new_GtCustomTrackClass() gt_custom_track_class_new
#define dao_gt_custom_track_script_wrapper_new_dao_hint_new_GtCustomTrackScriptWrapper() gt_custom_track_script_wrapper_new
#define dao_gt_custom_track_script_wrapper_new_dao_hint_new_GtCustomTrackScriptWrapper() gt_custom_track_script_wrapper_new
#define dao_gt_diagram_new_dao_hint_new_GtDiagram() gt_diagram_new
#define dao_gt_diagram_new_from_array_dao_hint_new_GtDiagram() gt_diagram_new_from_array
#define dao_gt_element_new_dao_hint_new_GtElement() gt_element_new
#define dao_gt_element_new_empty_dao_hint_new_GtElement() gt_element_new_empty
#define dao_gt_feature_index_memory_new_dao_hint_new_GtFeatureIndexMemory() gt_feature_index_memory_new
#define dao_gt_feature_index_class_new_dao_hint_new_GtFeatureIndexClass() gt_feature_index_class_new
#define dao_gt_feature_stream_new_dao_hint_new_GtFeatureStream() gt_feature_stream_new
#define dao_gt_feature_visitor_new_dao_hint_new_GtFeatureVisitor() gt_feature_visitor_new
#define dao_gt_graphics_cairo_new_dao_hint_new_GtGraphicsCairo() gt_graphics_cairo_new
#define dao_gt_graphics_cairo_new_from_context_dao_hint_new_GtGraphicsCairo() gt_graphics_cairo_new_from_context
#define dao_gt_graphics_class_new_dao_hint_new_GtGraphicsClass() gt_graphics_class_new
#define dao_gt_image_info_new_dao_hint_new_GtImageInfo() gt_image_info_new
#define dao_gt_layout_new_dao_hint_new_GtLayout() gt_layout_new
#define dao_gt_layout_new_with_twc_dao_hint_new_GtLayout() gt_layout_new_with_twc
#define dao_gt_line_new_dao_hint_new_GtLine() gt_line_new
#define dao_gt_line_breaker_bases_new_dao_hint_new_GtLineBreakerBases() gt_line_breaker_bases_new
#define dao_gt_line_breaker_captions_new_dao_hint_new_GtLineBreakerCaptions() gt_line_breaker_captions_new
#define dao_gt_line_breaker_class_new_dao_hint_new_GtLineBreakerClass() gt_line_breaker_class_new
#define dao_gt_rec_map_new_dao_hint_new_GtRecMap() gt_rec_map_new
#define dao_gt_style_new_dao_hint_new_GtStyle() gt_style_new
#define dao_gt_text_width_calculator_cairo_new_dao_hint_new_GtTextWidthCalculatorCairo() gt_text_width_calculator_cairo_new
#define dao_gt_text_width_calculator_class_new_dao_hint_new_GtTextWidthCalculatorClass() gt_text_width_calculator_class_new
#define dao_gt_track_new_dao_hint_new_GtTrack() gt_track_new
#define dao_gt_alphabet_new_dna_dao_hint_new_GtAlphabet() gt_alphabet_new_dna
#define dao_gt_alphabet_new_protein_dao_hint_new_GtAlphabet() gt_alphabet_new_protein
#define dao_gt_alphabet_new_empty_dao_hint_new_GtAlphabet() gt_alphabet_new_empty
#define dao_gt_alphabet_new_from_file_dao_hint_new_GtAlphabet() gt_alphabet_new_from_file
#define dao_gt_alphabet_new_from_file_no_suffix_dao_hint_new_GtAlphabet() gt_alphabet_new_from_file_no_suffix
#define dao_gt_alphabet_new_from_string_dao_hint_new_GtAlphabet() gt_alphabet_new_from_string
#define dao_gt_alphabet_new_from_sequence_dao_hint_new_GtAlphabet() gt_alphabet_new_from_sequence
#define dao_gt_array_new_dao_hint_new_GtArray() gt_array_new
#define dao_gt_bioseq_new_dao_hint_new_GtBioseq() gt_bioseq_new
#define dao_gt_bioseq_new_recreate_dao_hint_new_GtBioseq() gt_bioseq_new_recreate
#define dao_gt_bioseq_new_str_dao_hint_new_GtBioseq() gt_bioseq_new_str
#define dao_gt_bioseq_new_with_fasta_reader_dao_hint_new_GtBioseq() gt_bioseq_new_with_fasta_reader
#define dao_gt_bioseq_collection_new_dao_hint_new_GtBioseqCollection() gt_bioseq_collection_new
#define dao_gt_bioseq_iterator_new_dao_hint_new_GtBioseqIterator() gt_bioseq_iterator_new
#define dao_gt_bittab_new_dao_hint_new_GtBittab() gt_bittab_new
#define dao_gt_codon_iterator_encseq_new_dao_hint_new_GtCodonIteratorEncseq() gt_codon_iterator_encseq_new
#define dao_gt_codon_iterator_encseq_new_with_readmode_dao_hint_new_GtCodonIteratorEncseq() gt_codon_iterator_encseq_new_with_readmode
#define dao_gt_codon_iterator_class_new_dao_hint_new_GtCodonIteratorClass() gt_codon_iterator_class_new
#define dao_gt_codon_iterator_simple_new_dao_hint_new_GtCodonIteratorSimple() gt_codon_iterator_simple_new
#define dao_gt_GtCompactulongstore_new_dao_hint_new_GtGtCompactulongstore() gt_GtCompactulongstore_new
#define dao_gt_cstr_table_new_dao_hint_new_GtCstrTable() gt_cstr_table_new
#define dao_gt_desc_buffer_new_dao_hint_new_GtDescBuffer() gt_desc_buffer_new
#define dao_gt_disc_distri_new_dao_hint_new_GtDiscDistri() gt_disc_distri_new
#define dao_gt_dlist_new_dao_hint_new_GtDlist() gt_dlist_new
#define dao_gt_dynbittab_new_dao_hint_new_GtDynbittab() gt_dynbittab_new
#define dao_gt_encseq_encoder_new_from_options_dao_hint_new_GtEncseqEncoder() gt_encseq_encoder_new_from_options
#define dao_gt_encseq_loader_new_from_options_dao_hint_new_GtEncseqLoader() gt_encseq_loader_new_from_options
#define dao_gt_specialrangeiterator_new_dao_hint_new_GtSpecialrangeiterator() gt_specialrangeiterator_new
#define dao_gt_Viatwobitkeyvalues_new_dao_hint_new_GtViatwobitkeyvalues() gt_Viatwobitkeyvalues_new
#define dao_gt_encseq_encoder_new_dao_hint_new_GtEncseqEncoder() gt_encseq_encoder_new
#define dao_gt_encseq_loader_new_dao_hint_new_GtEncseqLoader() gt_encseq_loader_new
#define dao_gt_encseq_builder_new_dao_hint_new_GtEncseqBuilder() gt_encseq_builder_new
#define dao_gt_encseq_metadata_new_dao_hint_new_GtEncseqMetadata() gt_encseq_metadata_new
#define dao_gt_error_new_dao_hint_new_GtError() gt_error_new
#define dao_gt_example_a_new_dao_hint_new_GtExample_a() gt_example_a_new
#define dao_gt_example_b_new_dao_hint_new_GtExample_b() gt_example_b_new
#define dao_gt_fasta_reader_fsm_new_dao_hint_new_GtFastaReaderFsm() gt_fasta_reader_fsm_new
#define dao_gt_fasta_reader_rec_new_dao_hint_new_GtFastaReaderRec() gt_fasta_reader_rec_new
#define dao_gt_fasta_reader_seqit_new_dao_hint_new_GtFastaReaderSeqit() gt_fasta_reader_seqit_new
#define dao_gt_fastabuffer_new_dao_hint_new_GtFastabuffer() gt_fastabuffer_new
#define dao_gt_file_new_from_fileptr_dao_hint_new_GtFile() gt_file_new_from_fileptr
#define dao_gt_file_new_dao_hint_new_GtFile() gt_file_new
#define dao_gt_hashmap_new_dao_hint_new_GtHashmap() gt_hashmap_new
#define dao_gt_hashtable_new_dao_hint_new_GtHashtable() gt_hashtable_new
#define dao_gt_hashtable_new_with_start_size_dao_hint_new_GtHashtable() gt_hashtable_new_with_start_size
#define dao_gt_interval_tree_node_new_dao_hint_new_GtIntervalTreeNode() gt_interval_tree_node_new
#define dao_gt_interval_tree_new_dao_hint_new_GtIntervalTree() gt_interval_tree_new
#define dao_gt_io_new_dao_hint_new_GtIo() gt_io_new
#define dao_gt_logger_new_dao_hint_new_GtLogger() gt_logger_new
#define dao_gt_md5_tab_new_dao_hint_new_GtMD5Tab() gt_md5_tab_new
#define dao_gt_option_parser_new_dao_hint_new_GtOptionParser() gt_option_parser_new
#define dao_gt_option_new_bool_dao_hint_new_GtOption() gt_option_new_bool
#define dao_gt_option_new_double_dao_hint_new_GtOption() gt_option_new_double
#define dao_gt_option_new_double_min_dao_hint_new_GtOption() gt_option_new_double_min
#define dao_gt_option_new_double_min_max_dao_hint_new_GtOption() gt_option_new_double_min_max
#define dao_gt_option_new_probability_dao_hint_new_GtOption() gt_option_new_probability
#define dao_gt_option_new_int_dao_hint_new_GtOption() gt_option_new_int
#define dao_gt_option_new_int_min_dao_hint_new_GtOption() gt_option_new_int_min
#define dao_gt_option_new_int_max_dao_hint_new_GtOption() gt_option_new_int_max
#define dao_gt_option_new_int_min_max_dao_hint_new_GtOption() gt_option_new_int_min_max
#define dao_gt_option_new_uint_dao_hint_new_GtOption() gt_option_new_uint
#define dao_gt_option_new_uint_min_dao_hint_new_GtOption() gt_option_new_uint_min
#define dao_gt_option_new_uint_max_dao_hint_new_GtOption() gt_option_new_uint_max
#define dao_gt_option_new_uint_min_max_dao_hint_new_GtOption() gt_option_new_uint_min_max
#define dao_gt_option_new_long_dao_hint_new_GtOption() gt_option_new_long
#define dao_gt_option_new_ulong_dao_hint_new_GtOption() gt_option_new_ulong
#define dao_gt_option_new_ulong_min_dao_hint_new_GtOption() gt_option_new_ulong_min
#define dao_gt_option_new_ulong_min_max_dao_hint_new_GtOption() gt_option_new_ulong_min_max
#define dao_gt_option_new_range_dao_hint_new_GtOption() gt_option_new_range
#define dao_gt_option_new_range_min_max_dao_hint_new_GtOption() gt_option_new_range_min_max
#define dao_gt_option_new_string_dao_hint_new_GtOption() gt_option_new_string
#define dao_gt_option_new_string_array_dao_hint_new_GtOption() gt_option_new_string_array
#define dao_gt_option_new_choice_dao_hint_new_GtOption() gt_option_new_choice
#define dao_gt_option_new_filename_dao_hint_new_GtOption() gt_option_new_filename
#define dao_gt_option_new_filename_array_dao_hint_new_GtOption() gt_option_new_filename_array
#define dao_gt_option_new_debug_dao_hint_new_GtOption() gt_option_new_debug
#define dao_gt_option_new_verbose_dao_hint_new_GtOption() gt_option_new_verbose
#define dao_gt_option_new_width_dao_hint_new_GtOption() gt_option_new_width
#define dao_gt_outputfileinfo_new_dao_hint_new_GtOutputfileinfo() gt_outputfileinfo_new
#define dao_gt_queue_new_dao_hint_new_GtQueue() gt_queue_new
#define dao_gt_radixsort_new_ulong_dao_hint_new_GtRadixsort() gt_radixsort_new_ulong
#define dao_gt_radixsort_new_ulongpair_dao_hint_new_GtRadixsort() gt_radixsort_new_ulongpair
#define dao_gt_score_function_new_dao_hint_new_GtScoreFunction() gt_score_function_new
#define dao_gt_score_matrix_new_dao_hint_new_GtScoreMatrix() gt_score_matrix_new
#define dao_gt_score_matrix_new_read_protein_dao_hint_new_GtScoreMatrix() gt_score_matrix_new_read_protein
#define dao_gt_score_matrix_new_read_dao_hint_new_GtScoreMatrix() gt_score_matrix_new_read
#define dao_gt_seq_new_dao_hint_new_GtSeq() gt_seq_new
#define dao_gt_seq_new_own_dao_hint_new_GtSeq() gt_seq_new_own
#define dao_gt_seqiterator_fastq_new_dao_hint_new_GtSeqiteratorFastq() gt_seqiterator_fastq_new
#define dao_gt_seqiterator_colorspace_fastq_new_dao_hint_new_GtSeqiteratorColorspaceFastq() gt_seqiterator_colorspace_fastq_new
#define dao_gt_seqiterator_class_new_dao_hint_new_GtSeqiteratorClass() gt_seqiterator_class_new
#define dao_gt_seqiterator_sequence_buffer_new_dao_hint_new_GtSeqiteratorSequenceBuffer() gt_seqiterator_sequence_buffer_new
#define dao_gt_seqiterator_sequence_buffer_new_with_buffer_dao_hint_new_GtSeqiteratorSequenceBuffer() gt_seqiterator_sequence_buffer_new_with_buffer
#define dao_gt_sequence_buffer_new_guess_type_dao_hint_new_GtSequenceBuffer() gt_sequence_buffer_new_guess_type
#define dao_gt_sequence_buffer_embl_new_dao_hint_new_GtSequenceBufferEmbl() gt_sequence_buffer_embl_new
#define dao_gt_sequence_buffer_fasta_new_dao_hint_new_GtSequenceBufferFasta() gt_sequence_buffer_fasta_new
#define dao_gt_sequence_buffer_fastq_new_dao_hint_new_GtSequenceBufferFastq() gt_sequence_buffer_fastq_new
#define dao_gt_sequence_buffer_gb_new_dao_hint_new_GtSequenceBufferGb() gt_sequence_buffer_gb_new
#define dao_gt_sequence_buffer_plain_new_dao_hint_new_GtSequenceBufferPlain() gt_sequence_buffer_plain_new
#define dao_gt_splitter_new_dao_hint_new_GtSplitter() gt_splitter_new
#define dao_gt_str_new_dao_hint_new_GtStr() gt_str_new
#define dao_gt_str_new_cstr_dao_hint_new_GtStr() gt_str_new_cstr
#define dao_gt_str_array_new_file_dao_hint_new_GtStrArray() gt_str_array_new_file
#define dao_gt_str_array_new_dao_hint_new_GtStrArray() gt_str_array_new
#define dao_gt_str_cache_new_dao_hint_new_GtStrCache() gt_str_cache_new
#define dao_gt_string_distri_new_dao_hint_new_GtStringDistri() gt_string_distri_new
#define dao_gt_thread_new_dao_hint_new_GtThread() gt_thread_new
#define dao_gt_rwlock_new_dao_hint_new_GtRwlock() gt_rwlock_new
#define dao_gt_mutex_new_dao_hint_new_GtMutex() gt_mutex_new
#define dao_gt_timer_new_dao_hint_new_GtTimer() gt_timer_new
#define dao_gt_timer_new_with_progress_description_dao_hint_new_GtTimer() gt_timer_new_with_progress_description
#define dao_gt_tokenizer_new_dao_hint_new_GtTokenizer() gt_tokenizer_new
#define dao_gt_tool_new_dao_hint_new_GtTool() gt_tool_new
#define dao_gt_trans_table_new_dao_hint_new_GtTransTable() gt_trans_table_new
#define dao_gt_trans_table_new_standard_dao_hint_new_GtTransTable() gt_trans_table_new_standard
#define dao_gt_translator_new_with_table_dao_hint_new_GtTranslator() gt_translator_new_with_table
#define dao_gt_translator_new_dao_hint_new_GtTranslator() gt_translator_new
#define dao_gt_add_ids_stream_new_dao_hint_new_GtAddIdsStream() gt_add_ids_stream_new
#define dao_gt_add_ids_visitor_new_dao_hint_new_GtAddIdsVisitor() gt_add_ids_visitor_new
#define dao_gt_add_introns_stream_new_dao_hint_new_GtVisitorStream() gt_add_introns_stream_new
#define dao_gt_alignment_new_dao_hint_new_GtAlignment() gt_alignment_new
#define dao_gt_alignment_new_with_seqs_dao_hint_new_GtAlignment() gt_alignment_new_with_seqs
#define dao_gt_assembly_stats_calculator_new_dao_hint_new_GtAssemblyStatsCalculator() gt_assembly_stats_calculator_new
#define dao_gt_bed_in_stream_new_dao_hint_new_GtBEDInStream() gt_bed_in_stream_new
#define dao_gt_bed_parser_new_dao_hint_new_GtBEDParser() gt_bed_parser_new
#define dao_gt_bitinstream_new_dao_hint_new_GtBitinstream() gt_bitinstream_new
#define dao_gt_bitoutstream_new_dao_hint_new_GtBitoutstream() gt_bitoutstream_new
#define dao_gt_buffer_stream_new_dao_hint_new_GtBufferStream() gt_buffer_stream_new
#define dao_gt_cds_check_stream_new_dao_hint_new_GtCDSCheckStream() gt_cds_check_stream_new
#define dao_gt_cds_check_visitor_new_dao_hint_new_GtCDSCheckVisitor() gt_cds_check_visitor_new
#define dao_gt_cds_stream_new_dao_hint_new_GtCDSStream() gt_cds_stream_new
#define dao_gt_cds_visitor_new_dao_hint_new_GtCDSVisitor() gt_cds_visitor_new
#define dao_gt_chain_new_dao_hint_new_GtChain() gt_chain_new
#define dao_gt_chseqids_stream_new_dao_hint_new_GtChseqidsStream() gt_chseqids_stream_new
#define dao_gt_comment_node_new_dao_hint_new_GtCommentNode() gt_comment_node_new
#define dao_gt_csa_gene_new_dao_hint_new_GtCSAGene() gt_csa_gene_new
#define dao_gt_csa_splice_form_new_dao_hint_new_GtCSASpliceForm() gt_csa_splice_form_new
#define dao_gt_csa_stream_new_dao_hint_new_GtCSAStream() gt_csa_stream_new
#define dao_gt_csa_visitor_new_dao_hint_new_GtCSAVisitor() gt_csa_visitor_new
#define dao_gt_dup_feature_stream_new_dao_hint_new_GtDupFeatureStream() gt_dup_feature_stream_new
#define dao_gt_dup_feature_visitor_new_dao_hint_new_GtDupFeatureVisitor() gt_dup_feature_visitor_new
#define dao_gt_elias_gamma_bitwise_decoder_new_dao_hint_new_GtEliasGammaBitwiseDecoder() gt_elias_gamma_bitwise_decoder_new
#define dao_gt_eof_node_new_dao_hint_new_GtEOFNode() gt_eof_node_new
#define dao_gt_evaluator_new_dao_hint_new_GtEvaluator() gt_evaluator_new
#define dao_gt_extract_feature_stream_new_dao_hint_new_GtExtractFeatureStream() gt_extract_feature_stream_new
#define dao_gt_extract_feature_visitor_new_dao_hint_new_GtExtractFeatureVisitor() gt_extract_feature_visitor_new
#define dao_gt_feature_info_new_dao_hint_new_GtFeatureInfo() gt_feature_info_new
#define dao_gt_feature_node_new_dao_hint_new_GtFeatureNode() gt_feature_node_new
#define dao_gt_feature_node_new_pseudo_dao_hint_new_GtFeatureNode() gt_feature_node_new_pseudo
#define dao_gt_feature_node_new_pseudo_template_dao_hint_new_GtFeatureNode() gt_feature_node_new_pseudo_template
#define dao_gt_feature_node_new_standard_gene_dao_hint_new_GtFeatureNode() gt_feature_node_new_standard_gene
#define dao_gt_feature_node_iterator_new_dao_hint_new_GtFeatureNodeIterator() gt_feature_node_iterator_new
#define dao_gt_feature_node_iterator_new_direct_dao_hint_new_GtFeatureNodeIterator() gt_feature_node_iterator_new_direct
#define dao_gt_genome_node_class_new_dao_hint_new_GtGenomeNodeClass() gt_genome_node_class_new
#define dao_gt_gff3_in_stream_new_unsorted_dao_hint_new_GtGFF3InStream() gt_gff3_in_stream_new_unsorted
#define dao_gt_gff3_in_stream_new_sorted_dao_hint_new_GtGFF3InStream() gt_gff3_in_stream_new_sorted
#define dao_gt_gff3_in_stream_plain_new_unsorted_dao_hint_new_GtGFF3InStreamPlain() gt_gff3_in_stream_plain_new_unsorted
#define dao_gt_gff3_in_stream_plain_new_sorted_dao_hint_new_GtGFF3InStreamPlain() gt_gff3_in_stream_plain_new_sorted
#define dao_gt_gff3_out_stream_new_dao_hint_new_GtGFF3OutStream() gt_gff3_out_stream_new
#define dao_gt_gff3_parser_new_dao_hint_new_GtGFF3Parser() gt_gff3_parser_new
#define dao_gt_gff3_visitor_new_dao_hint_new_GtGFF3Visitor() gt_gff3_visitor_new
#define dao_gt_golomb_new_dao_hint_new_GtGolomb() gt_golomb_new
#define dao_gt_golomb_bitwise_decoder_new_dao_hint_new_GtGolombBitwiseDecoder() gt_golomb_bitwise_decoder_new
#define dao_gt_gtf_in_stream_new_dao_hint_new_GtGTFInStream() gt_gtf_in_stream_new
#define dao_gt_gtf_out_stream_new_dao_hint_new_GtGtfOutStream() gt_gtf_out_stream_new
#define dao_gt_gtf_parser_new_dao_hint_new_GtGtfParser() gt_gtf_parser_new
#define dao_gt_gtf_visitor_new_dao_hint_new_GtGtfVisitor() gt_gtf_visitor_new
#define dao_gt_hmm_new_dao_hint_new_GtHmm() gt_hmm_new
#define dao_gt_huffman_new_dao_hint_new_GtHuffman() gt_huffman_new
#define dao_gt_huffman_decoder_new_dao_hint_new_GtHuffmanDecoder() gt_huffman_decoder_new
#define dao_gt_huffman_decoder_new_from_memory_dao_hint_new_GtHuffmanDecoder() gt_huffman_decoder_new_from_memory
#define dao_gt_huffman_bitwise_decoder_new_dao_hint_new_GtHuffmanBitwiseDecoder() gt_huffman_bitwise_decoder_new
#define dao_gt_id_to_md5_stream_new_dao_hint_new_GtIDToMD5Stream() gt_id_to_md5_stream_new
#define dao_gt_id_to_md5_visitor_new_dao_hint_new_GtIdToMD5Visitor() gt_id_to_md5_visitor_new
#define dao_gt_inter_feature_stream_new_dao_hint_new_GtInterFeatureStream() gt_inter_feature_stream_new
#define dao_gt_inter_feature_visitor_new_dao_hint_new_GtInterFeatureVisitor() gt_inter_feature_visitor_new
#define dao_gt_mapping_new_dao_hint_new_GtMapping() gt_mapping_new
#define dao_gt_md5_to_id_stream_new_dao_hint_new_GtMD5ToIDStream() gt_md5_to_id_stream_new
#define dao_gt_md5_to_id_visitor_new_dao_hint_new_GtMD5ToIdVisitor() gt_md5_to_id_visitor_new
#define dao_gt_md5set_new_dao_hint_new_GtMD5set() gt_md5set_new
#define dao_gt_merge_feature_stream_new_dao_hint_new_GtMergeFeatureStream() gt_merge_feature_stream_new
#define dao_gt_merge_feature_visitor_new_dao_hint_new_GtMergeFeatureVisitor() gt_merge_feature_visitor_new
#define dao_gt_merge_stream_new_dao_hint_new_GtMergeStream() gt_merge_stream_new
#define dao_gt_node_stream_class_new_dao_hint_new_GtNodeStreamClass() gt_node_stream_class_new
#define dao_gt_node_visitor_class_new_dao_hint_new_GtNodeVisitorClass() gt_node_visitor_class_new
#define dao_gt_obo_parse_tree_new_dao_hint_new_GtOBOParseTree() gt_obo_parse_tree_new
#define dao_gt_orphanage_new_dao_hint_new_GtOrphanage() gt_orphanage_new
#define dao_gt_priorityqueue_new_dao_hint_new_GtPriorityqueue() gt_priorityqueue_new
#define dao_gt_rbtree_new_dao_hint_new_GtRbtree() gt_rbtree_new
#define dao_gt_rbtree_iter_new_from_first_dao_hint_new_GtRbtreeIter() gt_rbtree_iter_new_from_first
#define dao_gt_rbtree_iter_new_from_last_dao_hint_new_GtRbtreeIter() gt_rbtree_iter_new_from_last
#define dao_gt_region_mapping_new_mapping_dao_hint_new_GtRegionMapping() gt_region_mapping_new_mapping
#define dao_gt_region_mapping_new_seqfiles_dao_hint_new_GtRegionMapping() gt_region_mapping_new_seqfiles
#define dao_gt_region_mapping_new_rawseq_dao_hint_new_GtRegionMapping() gt_region_mapping_new_rawseq
#define dao_gt_region_node_new_dao_hint_new_GtRegionNode() gt_region_node_new
#define dao_gt_region_node_builder_new_dao_hint_new_GtRegionNodeBuilder() gt_region_node_builder_new
#define dao_gt_regioncov_visitor_new_dao_hint_new_GtRegioncovVisitor() gt_regioncov_visitor_new
#define dao_gt_rmq_new_dao_hint_new_GtRmq() gt_rmq_new
#define dao_gt_sam_alignment_new_dao_hint_new_GtSamAlignment() gt_sam_alignment_new
#define dao_gt_samfile_iterator_new_bam_dao_hint_new_GtSamfileIterator() gt_samfile_iterator_new_bam
#define dao_gt_samfile_iterator_new_sam_dao_hint_new_GtSamfileIterator() gt_samfile_iterator_new_sam
#define dao_gt_script_wrapper_stream_new_dao_hint_new_GtScriptWrapperStream() gt_script_wrapper_stream_new
#define dao_gt_script_wrapper_visitor_new_dao_hint_new_GtScriptWrapperVisitor() gt_script_wrapper_visitor_new
#define dao_gt_select_stream_new_dao_hint_new_GtSelectStream() gt_select_stream_new
#define dao_gt_select_visitor_new_dao_hint_new_GtSelectVisitor() gt_select_visitor_new
#define dao_gt_seqid2file_info_new_dao_hint_new_GtSeqid2fileInfo() gt_seqid2file_info_new
#define dao_gt_seqid2file_region_mapping_new_dao_hint_new_GtSeqid2fileRegionMapping() gt_seqid2file_region_mapping_new
#define dao_gt_seqid2seqnum_mapping_new_dao_hint_new_GtSeqid2seqnumMapping() gt_seqid2seqnum_mapping_new
#define dao_gt_sequence_node_new_dao_hint_new_GtSequenceNode() gt_sequence_node_new
#define dao_gt_shredder_new_dao_hint_new_GtShredder() gt_shredder_new
#define dao_gt_sort_stream_new_dao_hint_new_GtSortStream() gt_sort_stream_new
#define dao_gt_splice_site_info_stream_new_dao_hint_new_GtSpliceSiteInfoStream() gt_splice_site_info_stream_new
#define dao_gt_splice_site_info_visitor_new_dao_hint_new_GtSpliceSiteInfoVisitor() gt_splice_site_info_visitor_new
#define dao_gt_splicedseq_new_dao_hint_new_GtSplicedseq() gt_splicedseq_new
#define dao_gt_sspliced_alignment_new_dao_hint_new_GtSsplicedAlignment() gt_sspliced_alignment_new
#define dao_gt_stat_stream_new_dao_hint_new_GtStatStream() gt_stat_stream_new
#define dao_gt_stat_visitor_new_dao_hint_new_GtStatVisitor() gt_stat_visitor_new
#define dao_gt_stream_evaluator_new_dao_hint_new_GtStreamEvaluator() gt_stream_evaluator_new
#define dao_gt_targetbest_select_stream_new_dao_hint_new_GtTargetbestSelectStream() gt_targetbest_select_stream_new
#define dao_gt_tidy_region_node_stream_new_dao_hint_new_GtTidyRegionNodeStream() gt_tidy_region_node_stream_new
#define dao_gt_tidy_region_node_visitor_new_dao_hint_new_GtTidyRegionNodeVisitor() gt_tidy_region_node_visitor_new
#define dao_gt_toolbox_new_dao_hint_new_GtToolbox() gt_toolbox_new
#define dao_gt_transcript_bittabs_new_dao_hint_new_GtTranscriptBittabs() gt_transcript_bittabs_new
#define dao_gt_transcript_counts_new_dao_hint_new_GtTranscriptCounts() gt_transcript_counts_new
#define dao_gt_transcript_evaluators_new_dao_hint_new_GtTranscriptEvaluators() gt_transcript_evaluators_new
#define dao_gt_transcript_exons_new_dao_hint_new_GtTranscriptExons() gt_transcript_exons_new
#define dao_gt_transcript_used_exons_new_dao_hint_new_GtTranscriptUsedExons() gt_transcript_used_exons_new
#define dao_gt_type_checker_builtin_new_dao_hint_new_GtTypeCheckerBuiltin() gt_type_checker_builtin_new
#define dao_gt_type_checker_obo_new_dao_hint_new_GtTypeCheckerOBO() gt_type_checker_obo_new
#define dao_gt_uint64hashtable_new_dao_hint_new_GtUint64hashtable() gt_uint64hashtable_new
#define dao_gt_uniq_stream_new_dao_hint_new_GtUniqStream() gt_uniq_stream_new
#define dao_gt_visitor_stream_new_dao_hint_new_GtVisitorStream() gt_visitor_stream_new
#define dao_gth_ags_new_dao_hint_new_GthAgs() gth_ags_new
#define dao_gth_backtrace_path_new_dao_hint_new_GthBacktracePath() gth_backtrace_path_new
#define dao_gth_bssm_param_new_dao_hint_new_GthBssmParam() gth_bssm_param_new
#define dao_gth_call_info_new_dao_hint_new_GthCallInfo() gth_call_info_new
#define dao_gth_chain_collection_new_dao_hint_new_GthChainCollection() gth_chain_collection_new
#define dao_gth_desc_cache_new_dao_hint_new_GthDescCache() gth_desc_cache_new
#define dao_gth_dp_options_core_new_dao_hint_new_GthDpOptionsCore() gth_dp_options_core_new
#define dao_gth_dp_options_est_new_dao_hint_new_GthDpOptionsEst() gth_dp_options_est_new
#define dao_gth_dp_options_postpro_new_dao_hint_new_GthDpOptionsPostpro() gth_dp_options_postpro_new
#define dao_gth_dp_param_new_dao_hint_new_GthDpParam() gth_dp_param_new
#define dao_gth_dp_param_new_with_range_dao_hint_new_GthDpParam() gth_dp_param_new_with_range
#define dao_gth_dp_scores_protein_new_dao_hint_new_GthDpScoresProtein() gth_dp_scores_protein_new
#define dao_gth_gff3_pgl_visitor_new_dao_hint_new_GthGFF3PglVisitor() gth_gff3_pgl_visitor_new
#define dao_gth_gff3_sa_visitor_new_dao_hint_new_GthGFF3SaVisitor() gth_gff3_sa_visitor_new
#define dao_gthboolmatrix_new_dao_hint_new_gthboolmatrix() gthboolmatrix_new
#define dao_gth_chain_new_dao_hint_new_GthChain() gth_chain_new
#define dao_gthoutput_new_dao_hint_new_gthoutput() gthoutput_new
#define dao_gth_input_new_dao_hint_new_GthInput() gth_input_new
#define dao_gth_md5_cache_new_dao_hint_new_GthMD5Cache() gth_md5_cache_new
#define dao_gth_path_matrix_new_dao_hint_new_GthPathMatrix() gth_path_matrix_new
#define dao_gth_path_walker_new_dao_hint_new_GthPathWalker() gth_path_walker_new
#define dao_gth_pgl_new_dao_hint_new_GthPgl() gth_pgl_new
#define dao_gth_pgl_collection_new_dao_hint_new_GthPglCollection() gth_pgl_collection_new
#define dao_gth_region_factory_new_dao_hint_new_GthRegionFactory() gth_region_factory_new
#define dao_gth_sa_new_dao_hint_new_GthSa() gth_sa_new
#define dao_gth_sa_new_and_set_dao_hint_new_GthSa() gth_sa_new_and_set
#define dao_gth_sa_collection_new_dao_hint_new_GthSaCollection() gth_sa_collection_new
#define dao_gth_sa_collection_iterator_new_dao_hint_new_GthSaCollectionIterator() gth_sa_collection_iterator_new
#define dao_gth_sa_filter_new_dao_hint_new_GthSaFilter() gth_sa_filter_new
#define dao_gth_seq_col_class_new_dao_hint_new_GthSeqColClass() gth_seq_col_class_new
#define dao_gth_splice_site_model_new_dao_hint_new_GthSpliceSiteModel() gth_splice_site_model_new
#define dao_gth_spliced_seq_new_dao_hint_new_GthSplicedSeq() gth_spliced_seq_new
#define dao_gth_spliced_seq_new_with_comments_dao_hint_new_GthSplicedSeq() gth_spliced_seq_new_with_comments
#define dao_gth_stat_new_dao_hint_new_GthStat() gth_stat_new
#define dao_gth_txt_pgl_visitor_new_dao_hint_new_GthTxtPglVisitor() gth_txt_pgl_visitor_new
#define dao_gth_txt_sa_visitor_new_dao_hint_new_GthTxtSaVisitor() gth_txt_sa_visitor_new
#define dao_gth_xml_final_sa_visitor_new_dao_hint_new_GthXmlFinalSaVisitor() gth_xml_final_sa_visitor_new
#define dao_gth_xml_inter_sa_visitor_new_dao_hint_new_GthXmlInterSaVisitor() gth_xml_inter_sa_visitor_new
#define dao_gth_xml_pgl_visitor_new_dao_hint_new_GthXmlPglVisitor() gth_xml_pgl_visitor_new
#define dao_gtr_new_dao_hint_new_gtr() gtr_new
#define dao_gt_ltr_visitor_new_dao_hint_new_GtLtrVisitor() gt_ltr_visitor_new
#define dao_gt_ltrdigest_stream_new_dao_hint_new_GtLtrdigestStream() gt_ltrdigest_stream_new
#define dao_gt_ltr_fileout_stream_new_dao_hint_new_GtLtrFileoutStream() gt_ltr_fileout_stream_new
#define dao_gt_ltrharvest_fasta_out_stream_new_dao_hint_new_GtLtrharvestFastaOutStream() gt_ltrharvest_fasta_out_stream_new
#define dao_gt_ltrharvest_fasta_out_visitor_new_dao_hint_new_GtLtrharvestFastaOutVisitor() gt_ltrharvest_fasta_out_visitor_new
#define dao_gt_ltrharvest_stream_new_dao_hint_new_GtLtrharvestStream() gt_ltrharvest_stream_new
#define dao_gt_ltrharvest_tabout_stream_new_dao_hint_new_GtLtrharvestTaboutStream() gt_ltrharvest_tabout_stream_new
#define dao_gt_ltrharvest_tabout_visitor_new_dao_hint_new_GtLtrharvestTaboutVisitor() gt_ltrharvest_tabout_visitor_new
#define dao_gt_ltrharvest_tabout_visitor_new_longoutput_dao_hint_new_GtLtrharvestTaboutVisitor() gt_ltrharvest_tabout_visitor_new_longoutput
#define dao_gt_pdom_finder_new_dao_hint_new_GtPdomFinder() gt_pdom_finder_new
#define dao_gt_ppt_hmm_new_dao_hint_new_GtPptHmm() gt_ppt_hmm_new
#define dao_gt_bcktab_new_dao_hint_new_GtBcktab() gt_bcktab_new
#define dao_gt_chain_matchtable_new_dao_hint_new_GtChainMatchtable() gt_chain_matchtable_new
#define dao_gt_chain_chainmode_new_dao_hint_new_GtChainChainmode() gt_chain_chainmode_new
#define dao_gt_chain_chain_new_dao_hint_new_GtChainChain() gt_chain_chain_new
#define dao_gt_newbucketenumerator_dao_hint_new_gt() gt_newbucketenumerator
#define dao_gt_newGenBlockEncIdxSeq_dao_hint_new_gt() gt_newGenBlockEncIdxSeq
#define dao_gt_newBWTSeqContextRetrieverFactory_dao_hint_new_gt() gt_newBWTSeqContextRetrieverFactory
#define dao_gt_newBWTSeq_dao_hint_new_gt() gt_newBWTSeq
#define dao_gt_newEMIterator_dao_hint_new_gt() gt_newEMIterator
#define dao_gt_newMultiRangeAlphabetEncodingUInt8_dao_hint_new_gt() gt_newMultiRangeAlphabetEncodingUInt8
#define dao_gt_newCompositionList_dao_hint_new_gt() gt_newCompositionList
#define dao_gt_newSeqRangeList_dao_hint_new_gt() gt_newSeqRangeList
#define dao_gt_newSpecialsRankLookup_dao_hint_new_gt() gt_newSpecialsRankLookup
#define dao_gt_newSuffixarrayFileInterface_dao_hint_new_gt() gt_newSuffixarrayFileInterface
#define dao_gt_newSfxInterface_dao_hint_new_gt() gt_newSfxInterface
#define dao_gt_newSfxInterfaceWithReaders_dao_hint_new_gt() gt_newSfxInterfaceWithReaders
#define dao_gt_Bwtseqpositioniterator_new_dao_hint_new_GtBwtseqpositioniterator() gt_Bwtseqpositioniterator_new
#define dao_gt_newBwtSeqpositionextractor_dao_hint_new_gt() gt_newBwtSeqpositionextractor
#define dao_gt_Bwtseqcontextiterator_new_dao_hint_new_GtBwtseqcontextiterator() gt_Bwtseqcontextiterator_new
#define dao_gt_newenumpatterniterator_dao_hint_new_gt() gt_newenumpatterniterator
#define dao_gt_GtArrayGtBUItvinfo_new_dao_hint_new_GtGtArrayGtBUItvinfo() gt_GtArrayGtBUItvinfo_new
#define dao_gt_newLcpvalueiterator_dao_hint_new_gt() gt_newLcpvalueiterator
#define dao_gt_newmmsearchiteratorcomplete_plain_dao_hint_new_gt() gt_newmmsearchiteratorcomplete_plain
#define dao_gt_scannedprjkeytable_new_dao_hint_new_GtScannedprjkeytable() gt_scannedprjkeytable_new
#define dao_gt_newSequentialsuffixarrayreaderfromRAM_dao_hint_new_gt() gt_newSequentialsuffixarrayreaderfromRAM
#define dao_gt_newSequentialsuffixarrayreaderfromfile_dao_hint_new_gt() gt_newSequentialsuffixarrayreaderfromfile
#define dao_gt_sfx_multiesashulengthdist_new_dao_hint_new_GtSfxMultiesashulengthdist() gt_sfx_multiesashulengthdist_new
#define dao_gt_spmsk_inl_new_dao_hint_new_GtSpmskInl() gt_spmsk_inl_new
#define dao_gt_esa_lcpitvs_visitor_new_dao_hint_new_GtEsaLcpitvsVisitor() gt_esa_lcpitvs_visitor_new
#define dao_gt_esa_spmitvs_visitor_new_dao_hint_new_GtEsaSpmitvsVisitor() gt_esa_spmitvs_visitor_new
#define dao_gt_esa_visitor_info_new_dao_hint_new_GtEsaVisitorInfo() gt_esa_visitor_info_new
#define dao_gt_esa_visitor_class_new_dao_hint_new_GtEsaVisitorClass() gt_esa_visitor_class_new
#define dao_gt_leftborderbuffer_new_dao_hint_new_GtLeftborderbuffer() gt_leftborderbuffer_new
#define dao_gt_firstcodes_spacelog_new_dao_hint_new_GtFirstcodesSpacelog() gt_firstcodes_spacelog_new
#define dao_gt_newLimdfsresources_dao_hint_new_gt() gt_newLimdfsresources
#define dao_gt_newSWdpresource_dao_hint_new_gt() gt_newSWdpresource
#define dao_gt_windowiterator_new_dao_hint_new_GtWindowiterator() gt_windowiterator_new
#define dao_gt_marksubstring_new_dao_hint_new_GtMarksubstring() gt_marksubstring_new
#define dao_gt_newMyersonlineresources_dao_hint_new_gt() gt_newMyersonlineresources
#define dao_gt_pckbuckettable_new_dao_hint_new_GtPckbuckettable() gt_pckbuckettable_new
#define dao_gt_querymatch_new_dao_hint_new_GtQuerymatch() gt_querymatch_new
#define dao_gt_inl_queue_new_dao_hint_new_GtInlQueue() gt_inl_queue_new
#define dao_gt_contfinder_new_dao_hint_new_GtContfinder() gt_contfinder_new
#define dao_gt_contigs_writer_new_dao_hint_new_GtContigsWriter() gt_contigs_writer_new
#define dao_gt_spmfind_eqlen_state_new_dao_hint_new_GtSpmfindEqlenState() gt_spmfind_eqlen_state_new
#define dao_gt_spmfind_varlen_state_new_dao_hint_new_GtSpmfindVarlenState() gt_spmfind_varlen_state_new
#define dao_gt_readjoiner_ssar_new_dao_hint_new_GtReadjoinerSsar() gt_readjoiner_ssar_new
#define dao_gt_strgraph_new_dao_hint_new_GtStrgraph() gt_strgraph_new
#define dao_gt_strgraph_new_from_file_dao_hint_new_GtStrgraph() gt_strgraph_new_from_file
#define dao_gt_seqnumrelpos_new_dao_hint_new_GtSeqnumrelpos() gt_seqnumrelpos_new
#define dao_gt_blindtrie_new_dao_hint_new_GtBlindtrie() gt_blindtrie_new
#define dao_gt_copysort_new_dao_hint_new_GtCopysort() gt_copysort_new
#define dao_gt_differencecover_new_dao_hint_new_GtDifferencecover() gt_differencecover_new
#define dao_gt_Enumcodeatposition_new_dao_hint_new_GtEnumcodeatposition() gt_Enumcodeatposition_new
#define dao_gt_Outlcpinfo_new_dao_hint_new_GtOutlcpinfo() gt_Outlcpinfo_new
#define dao_gt_lcpvalues_rmq_new_dao_hint_new_GtLcpvaluesRmq() gt_lcpvalues_rmq_new
#define dao_gt_kmercodeiterator_encseq_new_dao_hint_new_GtKmercodeiteratorEncseq() gt_kmercodeiterator_encseq_new
#define dao_gt_kmercodeiterator_filetab_new_dao_hint_new_GtKmercodeiteratorFiletab() gt_kmercodeiterator_filetab_new
#define dao_gt_Sfxmappedrange_new_dao_hint_new_GtSfxmappedrange() gt_Sfxmappedrange_new
#define dao_gt_Sfxmappedrangelist_new_dao_hint_new_GtSfxmappedrangelist() gt_Sfxmappedrangelist_new
#define dao_gt_suftabparts_new_dao_hint_new_GtSuftabparts() gt_suftabparts_new
#define dao_gt_shortreadsort_new_dao_hint_new_GtShortreadsort() gt_shortreadsort_new
#define dao_gt_Sfxiterator_new_dao_hint_new_GtSfxiterator() gt_Sfxiterator_new
#define dao_gt_Sfxiterator_new_withadditionalvalues_dao_hint_new_GtSfxiterator() gt_Sfxiterator_new_withadditionalvalues
#define dao_gt_suffixsortspace_new_dao_hint_new_GtSuffixsortspace() gt_suffixsortspace_new
#define dao_gt_suffixsortspace_new_fromfile_dao_hint_new_GtSuffixsortspace() gt_suffixsortspace_new_fromfile
#define dao_gt_shu_unit_info_new_dao_hint_new_GtShuUnitInfo() gt_shu_unit_info_new
#define dao_gt_spmsuftab_new_dao_hint_new_GtSpmsuftab() gt_spmsuftab_new
#define dao_gt_substriter_new_dao_hint_new_GtSubstriter() gt_substriter_new
#define dao_gt_turningwheel_new_dao_hint_new_GtTurningwheel() gt_turningwheel_new
#define dao_gt_tyrindex_new_dao_hint_new_GtTyrindex() gt_tyrindex_new
#define dao_gt_tyrcountinfo_new_dao_hint_new_GtTyrcountinfo() gt_tyrcountinfo_new
#define dao_gt_tyrbckinfo_new_dao_hint_new_GtTyrbckinfo() gt_tyrbckinfo_new

#endif




#define x_dao_hint_delete_gt__block__delete() GtBlock
#define x_dao_hint_delete_gt__canvas__delete() GtCanvas
#define x_dao_hint_delete_gt__color__delete() GtColor
#define x_dao_hint_delete_gt__custom__track__delete() GtCustomTrack
#define x_dao_hint_delete_gt__diagram__delete() GtDiagram
#define x_dao_hint_delete_gt__element__delete() GtElement
#define x_dao_hint_delete_gt__feature__index__delete() GtFeatureIndex
#define x_dao_hint_delete_gt__graphics__delete() GtGraphics
#define x_dao_hint_delete_gt__image__info__delete() GtImageInfo
#define x_dao_hint_delete_gt__layout__delete() GtLayout
#define x_dao_hint_delete_gt__line__delete() GtLine
#define x_dao_hint_delete_gt__line__breaker__delete() GtLineBreaker
#define x_dao_hint_delete_gt__rec__map__delete() GtRecMap
#define x_dao_hint_delete_gt__style__delete__without__state() GtStyle
#define x_dao_hint_delete_gt__style__delete() GtStyle
#define x_dao_hint_delete_gt__text__width__calculator__delete() GtTextWidthCalculator
#define x_dao_hint_delete_gt__track__delete() GtTrack
#define x_dao_hint_delete_gt__alphabet__delete() GtAlphabet
#define x_dao_hint_delete_gt__array__delete() GtArray
#define x_dao_hint_delete_gt__bioseq__delete() GtBioseq
#define x_dao_hint_delete_gt__bioseq__collection__delete() GtBioseqCollection
#define x_dao_hint_delete_gt__bioseq__iterator__delete() GtBioseqIterator
#define x_dao_hint_delete_gt__bittab__delete() GtBittab
#define x_dao_hint_delete_gt__codon__iterator__delete() GtCodonIterator
#define x_dao_hint_delete_gt__GtCompactulongstore__delete() GtCompactUlongstore
#define x_dao_hint_delete_gt__cstr__table__delete() GtCstrTable
#define x_dao_hint_delete_gt__desc__buffer__delete() GtDescBuffer
#define x_dao_hint_delete_gt__disc__distri__delete() GtDiscDistri
#define x_dao_hint_delete_gt__dlist__delete() GtDlist
#define x_dao_hint_delete_gt__dynbittab__delete() GtDynBittab
#define x_dao_hint_delete_gt__specialrangeiterator__delete() GtSpecialrangeiterator
#define x_dao_hint_delete_gt__Viatwobitkeyvalues__delete() GtViatwobitkeyvalues
#define x_dao_hint_delete_gt__encseq__delete() GtEncseq
#define x_dao_hint_delete_gt__encseq__reader__delete() GtEncseqReader
#define x_dao_hint_delete_gt__encseq__encoder__delete() GtEncseqEncoder
#define x_dao_hint_delete_gt__encseq__loader__delete() GtEncseqLoader
#define x_dao_hint_delete_gt__encseq__builder__delete() GtEncseqBuilder
#define x_dao_hint_delete_gt__encseq__metadata__delete() GtEncseqMetadata
#define x_dao_hint_delete_gt__encseq__options__delete() GtEncseqOptions
#define x_dao_hint_delete_gt__error__delete() GtError
#define x_dao_hint_delete_gt__example__delete() GtExample
#define x_dao_hint_delete_gt__fasta__reader__delete() GtFastaReader
#define x_dao_hint_delete_gt__fastabuffer__delete() GtFastaBuffer
#define x_dao_hint_delete_gt__file__delete__without__handle() GtFile
#define x_dao_hint_delete_gt__file__delete() GtFile
#define x_dao_hint_delete_gt__hashmap__delete() GtHashmap
#define x_dao_hint_delete_gt__hashtable__delete() GtHashtable
#define x_dao_hint_delete_gt__interval__tree__delete() GtIntervalTree
#define x_dao_hint_delete_gt__io__delete() GtIO
#define x_dao_hint_delete_gt__logger__delete() GtLogger
#define x_dao_hint_delete_gt__md5__tab__delete() GtMD5Tab
#define x_dao_hint_delete_gt__option__parser__delete() GtOptionParser
#define x_dao_hint_delete_gt__option__delete() GtOption
#define x_dao_hint_delete_gt__outputfileinfo__delete() GtOutputFileInfo
#define x_dao_hint_delete_gt__queue__delete__with__contents() GtQueue
#define x_dao_hint_delete_gt__queue__delete() GtQueue
#define x_dao_hint_delete_gt__radixsort__delete() GtRadixsortinfo
#define x_dao_hint_delete_gt__score__function__delete() GtScoreFunction
#define x_dao_hint_delete_gt__score__matrix__delete() GtScoreMatrix
#define x_dao_hint_delete_gt__seq__delete() GtSeq
#define x_dao_hint_delete_gt__seqiterator__delete() GtSeqIterator
#define x_dao_hint_delete_gt__sequence__buffer__delete() GtSequenceBuffer
#define x_dao_hint_delete_gt__splitter__delete() GtSplitter
#define x_dao_hint_delete_gt__str__delete() GtStr
#define x_dao_hint_delete_gt__str__array__delete() GtStrArray
#define x_dao_hint_delete_gt__str__cache__delete() GtStrCache
#define x_dao_hint_delete_gt__string__distri__delete() GtStringDistri
#define x_dao_hint_delete_gt__thread__delete() GtThread
#define x_dao_hint_delete_gt__rwlock__delete() GtRWLock
#define x_dao_hint_delete_gt__mutex__delete() GtMutex
#define x_dao_hint_delete_gt__timer__delete() GtTimer
#define x_dao_hint_delete_gt__tokenizer__delete() GtTokenizer
#define x_dao_hint_delete_gt__tool__delete() GtTool
#define x_dao_hint_delete_gt__trans__table__delete() GtTransTable
#define x_dao_hint_delete_gt__translator__delete() GtTranslator
#define x_dao_hint_delete_gt__alignment__delete() GtAlignment
#define x_dao_hint_delete_gt__assembly__stats__calculator__delete() GtAssemblyStatsCalculator
#define x_dao_hint_delete_gt__bed__parser__delete() GtBEDParser
#define x_dao_hint_delete_gt__bitinstream__delete() GtBitInStream
#define x_dao_hint_delete_gt__bitoutstream__delete() GtBitOutStream
#define x_dao_hint_delete_gt__chain__delete() GtChain
#define x_dao_hint_delete_gt__csa__gene__delete() GtCSAGene
#define x_dao_hint_delete_gt__csa__splice__form__delete() GtCSASpliceForm
#define x_dao_hint_delete_gt__elias__gamma__bitwise__decoder__delete() GtEliasGammaBitwiseDecoder
#define x_dao_hint_delete_gt__evaluator__delete() GtEvaluator
#define x_dao_hint_delete_gt__feature__info__delete() GtFeatureInfo
#define x_dao_hint_delete_gt__feature__node__iterator__delete() GtFeatureNodeIterator
#define x_dao_hint_delete_gt__genome__node__delete() GtGenomeNode
#define x_dao_hint_delete_gt__gff3__parser__delete() GtGFF3Parser
#define x_dao_hint_delete_gt__golomb__delete() GtGolomb
#define x_dao_hint_delete_gt__golomb__bitwise__decoder__delete() GtGolombBitwiseDecoder
#define x_dao_hint_delete_gtf__parser__delete() GtGTFParser
#define x_dao_hint_delete_gt__hmm__delete() GtHMM
#define x_dao_hint_delete_gt__huffman__decoder__delete() GtHuffmanDecoder
#define x_dao_hint_delete_gt__huffman__delete() GtHuffman
#define x_dao_hint_delete_gt__huffman__bitwise__decoder__delete() GtHuffmanBitwiseDecoder
#define x_dao_hint_delete_gt__mapping__delete() GtMapping
#define x_dao_hint_delete_gt__md5set__delete() GtMD5Set
#define x_dao_hint_delete_gt__node__stream__delete() GtNodeStream
#define x_dao_hint_delete_gt__node__visitor__delete() GtNodeVisitor
#define x_dao_hint_delete_gt__obo__parse__tree__delete() GtOBOParseTree
#define x_dao_hint_delete_gt__orphanage__delete() GtOrphanage
#define x_dao_hint_delete_gt__priorityqueue__delete__min() GtPriorityQueue
#define x_dao_hint_delete_gt__priorityqueue__delete() GtPriorityQueue
#define x_dao_hint_delete_gt__rbtree__delete() GtRBTree
#define x_dao_hint_delete_gt__rbtree__iter__delete() GtRBTreeIter
#define x_dao_hint_delete_gt__region__mapping__delete() GtRegionMapping
#define x_dao_hint_delete_gt__region__node__builder__delete() GtRegionNodeBuilder
#define x_dao_hint_delete_gt__rmq__delete() GtRMQ
#define x_dao_hint_delete_gt__sam__alignment__delete() GtSamAlignment
#define x_dao_hint_delete_gt__samfile__iterator__delete() GtSamfileIterator
#define x_dao_hint_delete_gt__seqid2file__info__delete() GtSeqid2FileInfo
#define x_dao_hint_delete_gt__seqid2seqnum__mapping__delete() GtSeqid2SeqnumMapping
#define x_dao_hint_delete_gt__shredder__delete() GtShredder
#define x_dao_hint_delete_gt__splicedseq__delete() Splicedseq
#define x_dao_hint_delete_gt__sspliced__alignment__delete() GtSSplicedAlignment
#define x_dao_hint_delete_gt__stream__evaluator__delete() GtStreamEvaluator
#define x_dao_hint_delete_gt__toolbox__delete() GtToolbox
#define x_dao_hint_delete_gt__transcript__bittabs__delete() GtTranscriptBittabs
#define x_dao_hint_delete_gt__transcript__counts__delete() GtTranscriptCounts
#define x_dao_hint_delete_gt__transcript__evaluators__delete() GtTranscriptEvaluators
#define x_dao_hint_delete_gt__transcript__exons__delete() GtTranscriptExons
#define x_dao_hint_delete_gt__transcript__used__exons__delete() GtTranscriptUsedExons
#define x_dao_hint_delete_gt__type__checker__delete() GtTypeChecker
#define x_dao_hint_delete_gt__uint64hashtable__delete() GtUint64hashtable
#define x_dao_hint_delete_gth__ags__delete() GthAGS
#define x_dao_hint_delete_gth__backtrace__path__delete() GthBacktracePath
#define x_dao_hint_delete_gth__bssm__param__delete() GthBSSMParam
#define x_dao_hint_delete_gth__call__info__delete() GthCallInfo
#define x_dao_hint_delete_gth__chain__collection__delete() GthChainCollection
#define x_dao_hint_delete_gth__desc__cache__delete() GthDescCache
#define x_dao_hint_delete_gth__dp__options__core__delete() GthDPOptionsCore
#define x_dao_hint_delete_gth__dp__options__est__delete() GthDPOptionsEST
#define x_dao_hint_delete_gth__dp__options__postpro__delete() GthDPOptionsPostpro
#define x_dao_hint_delete_gth__dp__param__delete() GthDPParam
#define x_dao_hint_delete_gth__dp__scores__protein__delete() GthDPScoresProtein
#define x_dao_hint_delete_gthboolmatrix__delete() GthBoolMatrix
#define x_dao_hint_delete_gth__chain__delete() GthChain
#define x_dao_hint_delete_gthoutput__delete() GthOutput
#define x_dao_hint_delete_gth__input__delete__current() GthInput
#define x_dao_hint_delete_gth__input__delete__complete() GthInput
#define x_dao_hint_delete_gth__md5__cache__delete() GthMD5Cache
#define x_dao_hint_delete_gth__path__matrix__delete() GthPathMatrix
#define x_dao_hint_delete_gth__path__walker__delete() GthPathWalker
#define x_dao_hint_delete_gth__pgl__delete() GthPGL
#define x_dao_hint_delete_gth__pgl__collection__delete() GthPGLCollection
#define x_dao_hint_delete_gth__pgl__visitor__delete() GthPGLVisitor
#define x_dao_hint_delete_gth__region__factory__delete() GthRegionFactory
#define x_dao_hint_delete_gth__sa__delete() GthSA
#define x_dao_hint_delete_gth__sa__collection__delete() GthSACollection
#define x_dao_hint_delete_gth__sa__collection__iterator__delete() GthSACollectionIterator
#define x_dao_hint_delete_gth__sa__filter__delete() GthSAFilter
#define x_dao_hint_delete_gth__sa__visitor__delete() GthSAVisitor
#define x_dao_hint_delete_gth__seq__col__delete() GthSeqCol
#define x_dao_hint_delete_gth__splice__site__model__delete() GthSpliceSiteModel
#define x_dao_hint_delete_gth__spliced__seq__delete() GthSplicedSeq
#define x_dao_hint_delete_gth__stat__delete() GthStat
#define x_dao_hint_delete_gtr__delete() GtR
#define x_dao_hint_delete_gt__pbs__results__delete() GtPBSResults
#define x_dao_hint_delete_gt__pdom__finder__delete() GtPdomFinder
#define x_dao_hint_delete_gt__pdom__results__delete() GtPdomResults
#define x_dao_hint_delete_gt__ppt__results__delete() GtPPTResults
#define x_dao_hint_delete_gt__bcktab__delete() GtBcktab
#define x_dao_hint_delete_gt__chain__matchtable__delete() GtChain2Dimmatchtable
#define x_dao_hint_delete_gt__chain__chainmode__delete() GtChain2Dimmode
#define x_dao_hint_delete_gt__chain__chain__delete() GtChain2Dim
#define x_dao_hint_delete_gt__deleteBWTSeqContextRetrieverFactory() BWTSeqContextRetrieverFactory
#define x_dao_hint_delete_gt__deleteBWTSeqCR() BWTSeqContextRetriever
#define x_dao_hint_delete_gt__deleteBWTSeq() BWTSeq
#define x_dao_hint_delete_gt__deleteEMIterator() BWTSeqExactMatchesIterator
#define x_dao_hint_delete_gt__deleteEncIdxSeq() EISeq
#define x_dao_hint_delete_gt__deleteCompositionList() compList
#define x_dao_hint_delete_gt__deleteSeqRangeList() seqRangeList
#define x_dao_hint_delete_gt__deleteSpecialsRankLookup() SpecialsRankLookup
#define x_dao_hint_delete_gt__deleteSuffixarrayFileInterface() SuffixarrayFileInterface
#define x_dao_hint_delete_gt__deleteSfxInterface() sfxInterface
#define x_dao_hint_delete_gt__Bwtseqpositioniterator__delete() Bwtseqpositioniterator
#define x_dao_hint_delete_gt__Bwtseqcontextiterator__delete() Bwtseqcontextiterator
#define x_dao_hint_delete_gt__deletevoidBWTSeq() FMindex
#define x_dao_hint_delete_gt__scannedprjkeytable__delete() GtScannedprjkeytable
#define x_dao_hint_delete_gt__esa__visitor__delete() GtESAVisitor
#define x_dao_hint_delete_gt__firstcodes__spacelog__delete() GtFirstcodesspacelog
#define x_dao_hint_delete_gt__index__options__delete() GtIndexOptions
#define x_dao_hint_delete_gt__windowiterator__delete() Windowiterator
#define x_dao_hint_delete_gt__mergertrie__delete() Mergertrierep
#define x_dao_hint_delete_gt__pckbuckettable__delete() Pckbuckettable
#define x_dao_hint_delete_gt__querymatch__delete() Querymatch
#define x_dao_hint_delete_gt__contfinder__delete() GtContfinder
#define x_dao_hint_delete_gt__contigs__writer__delete() GtContigsWriter
#define x_dao_hint_delete_gt__readjoiner__ssar__delete() Sequentialsuffixarrayreader
#define x_dao_hint_delete_gt__strgraph__delete() GtStrgraph
#define x_dao_hint_delete_gt__seqnumrelpos__delete() GtSeqnumrelpos
#define x_dao_hint_delete_gt__blindtrie__delete() GtBlindtrie
#define x_dao_hint_delete_gt__copysort__delete() GtBucketspec2
#define x_dao_hint_delete_gt__differencecover__delete() GtDifferencecover
#define x_dao_hint_delete_gt__Enumcodeatposition__delete() Enumcodeatposition
#define x_dao_hint_delete_gt__Outlcpinfo__delete() GtOutlcpinfo
#define x_dao_hint_delete_gt__kmercodeiterator__delete() GtKmercodeiterator
#define x_dao_hint_delete_gt__Sfxmappedrange__delete() GtSfxmappedrange
#define x_dao_hint_delete_gt__Sfxmappedrangelist__delete() GtSfxmappedrangelist
#define x_dao_hint_delete_gt__sfxoptions__delete() Suffixeratoroptions
#define x_dao_hint_delete_gt__suftabparts__delete() GtSuftabparts
#define x_dao_hint_delete_gt__shortreadsort__delete() GtShortreadsortworkinfo
#define x_dao_hint_delete_gt__suffixsortspace__sortspace__delete() GtSuffixsortspace
#define x_dao_hint_delete_gt__spmsuftab__delete() GtSpmsuftab
#define x_dao_hint_delete_gt__turningwheel__delete() Turningwheel





#include "genometools.h"

#include "core/alphabet_api.h"
#include "core/array2dim_api.h"
#include "core/array_api.h"
#include "core/assert_api.h"
#include "core/basename_api.h"
#include "core/bittab_api.h"
#include "core/bsearch_api.h"
#include "core/countingsort_api.h"
#include "core/cstr_api.h"
#include "core/cstr_table_api.h"
#include "core/dlist_api.h"
#include "core/encseq_api.h"
#include "core/endianess_api.h"
#include "core/error_api.h"
#include "core/file_api.h"
#include "core/fileutils_api.h"
#include "core/fptr_api.h"
#include "core/grep_api.h"
#include "core/hashmap_api.h"
#include "core/init_api.h"
#include "core/interval_tree_api.h"
#include "core/log_api.h"
#include "core/logger_api.h"
#include "core/ma_api.h"
#include "core/msort_api.h"
#include "core/parseutils_api.h"
#include "core/option_api.h"
#include "core/phase_api.h"
#include "core/qsort_r_api.h"
#include "core/queue_api.h"
#include "core/range_api.h"
#include "core/readmode_api.h"
#include "core/splitter_api.h"
#include "core/str_api.h"
#include "core/str_array_api.h"
#include "core/strand_api.h"
#include "core/strcmp_api.h"
#include "core/symbol_api.h"
#include "core/timer_api.h"
#include "core/translator_api.h"
#include "core/types_api.h"
#include "core/undef_api.h"
#include "core/unused_api.h"
#include "core/version_api.h"
#include "core/warning_api.h"
#include "core/xansi_api.h"

/* the extended module */
#include "extended/add_introns_stream_api.h"
#include "extended/bed_in_stream_api.h"
#include "extended/comment_node_api.h"
#include "extended/csa_stream_api.h"
#include "extended/cds_stream_api.h"
#include "extended/eof_node_api.h"
#include "extended/extract_feature_stream_api.h"
#include "extended/feature_node_api.h"
#include "extended/feature_node_iterator_api.h"
#include "extended/genome_node_api.h"
#include "extended/gff3_in_stream_api.h"
#include "extended/gff3_out_stream_api.h"
#include "extended/gff3_parser_api.h"
#include "extended/gff3_visitor_api.h"
#include "extended/gtf_in_stream_api.h"
#include "extended/id_to_md5_stream_api.h"
#include "extended/inter_feature_stream_api.h"
#include "extended/md5_to_id_stream_api.h"
#include "extended/merge_feature_stream_api.h"
#include "extended/merge_stream_api.h"
#include "extended/node_stream_api.h"
#include "extended/node_visitor_api.h"
#include "extended/region_mapping_api.h"
#include "extended/region_node_api.h"
#include "extended/select_stream_api.h"
#include "extended/sequence_node_api.h"
#include "extended/sort_stream_api.h"
#include "extended/stat_stream_api.h"
#include "extended/tag_value_map_api.h"
#include "extended/type_checker_api.h"
#include "extended/type_checker_obo_api.h"
#include "extended/uniq_stream_api.h"
#include "extended/visitor_stream_api.h"

#include "annotationsketch/rec_map.h"

#ifndef WITHOUT_CAIRO
/* the AnnotationSketch module (depends on Cairo) */
#include "annotationsketch/block_api.h"
#include "annotationsketch/canvas_api.h"
#include "annotationsketch/canvas_cairo_context_api.h"
#include "annotationsketch/canvas_cairo_file_api.h"
#include "annotationsketch/color_api.h"
#include "annotationsketch/custom_track_api.h"
#include "annotationsketch/custom_track_gc_content_api.h"
#include "annotationsketch/custom_track_script_wrapper_api.h"
#include "annotationsketch/diagram_api.h"
#include "annotationsketch/feature_index_api.h"
#include "annotationsketch/feature_index_memory_api.h"
#include "annotationsketch/graphics_api.h"
#include "annotationsketch/image_info_api.h"
#include "annotationsketch/layout_api.h"
#include "annotationsketch/rec_map_api.h"
#include "annotationsketch/style_api.h"
#include "annotationsketch/text_width_calculator_api.h"
#include "annotationsketch/text_width_calculator_cairo_api.h"
#endif
